import { StyleSheet } from 'react-native';

const stylesDefault = StyleSheet.create({
  blue: { color: '#0d6efd' },
  blueLight: { color: '#8cb8f9' },
  indigo: { color: '#6610f2' },
  indigoLight: { color: '#b78ff8' },
  purple: { color: '#6f42c1' },
  purpleLight: { color: '#b790ff' },
  pink: { color: '#d63384' },
  pinkLight: { color: '#d585ad' },
  red: { color: '#dc3545' },
  redLight: { color: '#f2848f' },
  orange: { color: '#fd7e14' },
  orangeLight: { color: '#dda77a' },
  yellow: { color: '#ffc107' },
  yellowLight: { color: '#e2cf97' },
  green: { color: '#198754' },
  greenLight: { color: '#73e4b0' },
  teal: { color: '#20c997' },
  tealLight: { color: '#8be2c8' },
  cyan: { color: '#0dcaf0' },
  cyanLight: { color: '#89dbeb' },
  gray: { color: 'gray' },
  grayLight: { color: '#ede9e9' },
  // Background colors
  blueBg: { backgroundColor: '#0d6efd' },
  blueLightBg: { backgroundColor: '#8cb8f9' },
  indigoBg: { backgroundColor: '#6610f2' },
  indigoLightBg: { backgroundColor: '#b78ff8' },
  purpleBg: { backgroundColor: '#6f42c1' },
  purpleLightBg: { backgroundColor: '#b790ff' },
  pinkBg: { backgroundColor: '#d63384' },
  pinkLightBg: { backgroundColor: '#d585ad' },
  redBg: { backgroundColor: '#dc3545' },
  redLightBg: { backgroundColor: '#f2848f' },
  orangeBg: { backgroundColor: '#fd7e14' },
  orangeLightBg: { backgroundColor: '#dda77a' },
  yellowBg: { backgroundColor: '#ffc107' },
  yellowLightBg: { backgroundColor: '#e2cf97' },
  greenBg: { backgroundColor: '#198754' },
  greenLightBg: { backgroundColor: '#73e4b0' },
  tealBg: { backgroundColor: '#20c997' },
  tealLightBg: { backgroundColor: '#8be2c8' },
  cyanBg: { backgroundColor: '#0dcaf0' },
  cyanLightBg: { backgroundColor: '#89dbeb' },
  grayBg: { backgroundColor: 'gray' },
  grayLightBg: { backgroundColor: '#fbfbfb' },
  semiGreenBg: { backgroundColor: '#afafaf'},
  semiPurpleBg: { backgroundColor: '#8a5a9b'},
  color_primary: { color: "#69A42F" },
  color_secondary: { color: "#3E1054" },

  btnConfirmar: { color: "#d4d9fa" },
  btnCancelar: { color: "#e3e6fd" },
  subtitles: {
    fontSize: 24,
    fontWeight: '700',
    fontFamily: 'Cochin',
    padding: 10,
  },
});

export default stylesDefault;

